-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgpWfXFGCvYOerKk+h
PVcOPb5H8XMGsE5aUTsC6d32lNSgCgYIKoZIzj0DAQehRANCAAQR+dIfbYaC8QS0
6i2OpnFzfI3JqKuajKw1Um+tzKgRmzrLFgOAmDAX47DiWfB8rQzcrvUyhtLIb2F3
aWEZo4FA
-----END PRIVATE KEY-----