// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgqqGV0DkD1tansbvFcsAyGfwUyyHJPYw',
    appId: '1:3520181018:android:77ba6fa4b7f7b2136f32a3',
    messagingSenderId: '3520181018',
    projectId: 'pulstrade-fb01a',
    storageBucket: 'pulstrade-fb01a.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0KeXZXpYE1lt0f79VKYbH-9pBKserSiw',
    appId: '1:3520181018:web:0fd4e3841a8603a66f32a3',
    messagingSenderId: '3520181018',
    projectId: 'pulstrade-fb01a',
    authDomain: 'pulstrade-fb01a.firebaseapp.com',
    storageBucket: 'pulstrade-fb01a.firebasestorage.app',
    measurementId: 'G-VNMG3R6NRP',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2i1j8z4xaZ6h9wnrjr716if0xvfgzvuY',
    appId: '1:3520181018:ios:2272fdb67307bfca6f32a3',
    messagingSenderId: '3520181018',
    projectId: 'pulstrade-fb01a',
    storageBucket: 'pulstrade-fb01a.firebasestorage.app',
    androidClientId: '3520181018-dfemnl2dh9405t5ivmsnbgla73svlk7n.apps.googleusercontent.com',
    iosClientId: '3520181018-74m18lv5vrb9i7ue6i8s1bu5geb8qcko.apps.googleusercontent.com',
    iosBundleId: 'com.pulstrade',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2i1j8z4xaZ6h9wnrjr716if0xvfgzvuY',
    appId: '1:3520181018:ios:a658cc6d9009fa0e6f32a3',
    messagingSenderId: '3520181018',
    projectId: 'pulstrade-fb01a',
    storageBucket: 'pulstrade-fb01a.firebasestorage.app',
    androidClientId: '3520181018-dfemnl2dh9405t5ivmsnbgla73svlk7n.apps.googleusercontent.com',
    iosClientId: '3520181018-qoug4kdmd33ooeju4giicl47rfo52avu.apps.googleusercontent.com',
    iosBundleId: 'com.davidalizadeh.pulstrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0KeXZXpYE1lt0f79VKYbH-9pBKserSiw',
    appId: '1:3520181018:web:d004275d5557d98f6f32a3',
    messagingSenderId: '3520181018',
    projectId: 'pulstrade-fb01a',
    authDomain: 'pulstrade-fb01a.firebaseapp.com',
    storageBucket: 'pulstrade-fb01a.firebasestorage.app',
    measurementId: 'G-B3TF3S6TG7',
  );
}
